### ISSUE TITLE
Add the ability to find a match via regex

### ISSUE THREAD

**Issue by mcdonnelldean** [mcollina/bloomrun#15]
__EG:__ `bloomrun.lookup({role: 'foo', cmd: /.*/}) `

**Comment by mcollina** [comment]
I'm :+1: on this.

The basic use case should be done adding another case here https://github.com/mcollina/bloomrun/blob/master/lib/deepPartialMatch.js#L6-L10 and not considering the regexp in https://github.com/mcollina/bloomrun/blob/master/lib/genKeys.js#L3-L8.

I think that should give us a decent performance level if any other property is added to the lookup call, as is `role: 'foo'` in your example.

**Comment by mcdonnelldean** [comment]
Agreed, I'll take a look at implementing when I get a free cycle (weekend possibly)

**Comment by mcollina** [comment]
I think we should support regexps both in the `add` and in the `lookup`.

Why it does not like it?

**Comment by mcollina** [comment]
@mcdonnelldean is this fixed in https://github.com/mcollina/bloomrun/pull/21? Is that ok for you for general release?

**Comment by mcdonnelldean** [comment]
Added via #21
