### ISSUE TITLE
Create the ability to 'remove' a pattern

### ISSUE THREAD

**Issue by mcdonnelldean** [mcollina/bloomrun#2]
@mcollina could you put your thoughts around how this is done here? I don't mind tackling it tonight as it will allow me to push out a new version of Nanite.

**Comment by mcollina** [comment]
The best way would be to get the matching bucket, remove the relative entry, and then regenerate the bloom filter only with the remaining entries. Is it clear?

**Comment by mcdonnelldean** [comment]
@mcollina, sort of, not sure how to regenerate without re adding them all via the .add method

**Comment by mcollina** [comment]
For each pattern, do https://github.com/mcollina/bloomrun/blob/master/bloomrun.js#L35

**Comment by mcollina** [comment]
and you would need to reinitialize https://github.com/mcollina/bloomrun/blob/master/lib/bucket.js#L6-L9

**Comment by mcdonnelldean** [comment]
Awesome, if I get stuck I'll ping you.

**Comment by mcdonnelldean** [comment]
:+1:

**Comment by mcollina** [comment]
Released in 0.3.0.
