### ISSUE TITLE
add a destroy method

### ISSUE THREAD

**Issue by davidmarkclements** [mcollina/bloomrun#29]
it would be nice if we could do explicit cleanup 

```
bloom.destroy() // remove all patterns and clean up any internal refs
```

**Comment by mcollina** [comment]
The question for having a `bloom.destroy()` is what is the state after doing so. Can you still add new patterns to it? If not, why don't you just do `bloom = bloomrun()`?

**Comment by mcdonnelldean** [comment]
@davidmarkclements comment on the above?

**Comment by davidmarkclements** [comment]
I forget my thought process around this - perhaps a `bloom.clear()` so you can add patterns again

**Comment by mcdonnelldean** [comment]
So `bloomrun.clear()` would be nice as long as it but I think it would ultimately be sugar over `bloom = bloomrun()`. Honestly though, I've yet to come across a time where it made sense to clear down patterns at runtime since the fault from that was usually a big issue.

**Comment by mcdonnelldean** [comment]
@mcollina Thoughts on this? I still haven't found a use case to be honest.

**Comment by mcollina** [comment]
So, I'm 👎 , I think we can close this for now. Feel free to reopen this at any time.
