### ISSUE TITLE
safeEqual is not safe

### ISSUE THREAD

**Issue by StarpTech** [mcollina/bloomrun#46]
@mcollina 

How to reproduce
```js
'use strict';

const Bloomrun = require('bloomrun');

let catalog = Bloomrun()

for (var index = 0; index < 100; index++) {

  let pattern = {
    topic: 'math',
    cmd: 'add' + index
  };

  let value = catalog.lookup(pattern);

  if (value) {
    console.log(pattern)
    throw "Already registered!"
  }

  catalog.add(pattern, index);

}
```

The bug is in `safeEqual`

```js
console.log(safeEqual('add1', 'add10')) // true
```

You don't iterate the longest string. `add1` is equals with `add10` because the character add1[1,3] is equals to add10[1,3]

https://github.com/mcollina/bloomrun/blob/master/lib/safeEqual.js#L10

**Comment by StarpTech** [comment]
I create a PR https://github.com/mcollina/bloomrun/pull/47

**Comment by StarpTech** [comment]
@mcollina In which case we couldn't use a ''===' ?

**Comment by mcollina** [comment]
This is it https://github.com/mcollina/bloomrun/issues/30
