### ISSUE TITLE
test: Remove pattern with regex

### ISSUE THREAD

**Issue by gabssnake** [mcollina/bloomrun#48]
Hi there, hope you are doing good.
Is there a way to remove a pattern that contains only a regex, as the one in the readme?

```js
bloomrun.add({say: /.*/}, 'Matched with a regexp!')
```

Tried the following test:
```js
// Test passes
test('removing regex pattern (with other keys) is supported', function (t) {
  t.plan(2)
  var instance = bloomrun()
  var pattern = { say: 'something', to: /.*/ }
  instance.add(pattern)
  t.deepEqual(instance.lookup({ say: 'something', to: 'you' }), pattern)
  instance.remove(pattern)
  t.equal(instance.lookup({ say: 'something', to: 'you' }), null)
})

// Fails: expected null, got { to: /.*/ } to the final lookup
test('removing regex pattern (without other keys) is supported', function (t) {
  t.plan(2)
  var instance = bloomrun()
  var pattern = { to: /.*/ }
  instance.add(pattern)
  t.deepEqual(instance.lookup({ to: 'you' }), pattern)
  instance.remove(pattern)
  t.equal(instance.lookup({ to: 'you' }), null)
})
```

**Comment by mcollina** [comment]
Good find! Would you like to send a PR? We are all maxed out atm, and it might take a while otherwise.

**Comment by vdakalov** [comment]
Guys, please look at this

https://github.com/mcollina/bloomrun/blob/3c5a02c34a993983e66efb7e7a117b39299875fa/test.js#L173

The test is fail when I use `/^[a-zA-Z0-9-.]+$/i` as pattern.

Just replace pattern in test and execute it.

**Comment by mcollina** [comment]
Would you mind sending a PR with a fix?

also cc @StarpTech

**Comment by StarpTech** [comment]
Atm no capacity to fix that but I will have an eye on the PR.
