### ISSUE TITLE
Where is the bloom filter in bloomrun?

### ISSUE THREAD

**Issue by StarpTech** [mcollina/bloomrun#56]
Hi, this is a question about the internal implementation of bloomrun. In the descriptions I read

```
A js pattern matcher based on bloom filters
```

Where can I find the implementation of a [bloom filter](https://en.wikipedia.org/wiki/Bloom_filter) ? What do you mean with `based on`? Would be nice to clarify that and besides thanks for this great library!

**Comment by mcollina** [comment]
Since version 3 this is not using bloom filters anymore. A reference remained in the `package.json`. I have just removed it.

**Comment by StarpTech** [comment]
And just as hint the repo descriptions contains it too.
