### ISSUE TITLE
binaries in javascript file

### ISSUE THREAD

**Issue by veeramarni** [mcollina/bloomrun#66]
Our build failed since it cannot read `safeEqual.js` file. I'm using MacOs and this package is downloaded through `nats-hemera` with version `4.0.0`. We are hitting this error recently.

File out shows as below. 
![image](https://user-images.githubusercontent.com/3382355/36284185-c40912fa-1274-11e8-87c8-da3eaf9725df.png)

Error
--
![image](https://user-images.githubusercontent.com/3382355/36284460-bbfdacfa-1275-11e8-9332-27fd17373456.png)

**Comment by veeramarni** [comment]
Noticed, when we delete the package it is working fine as the file appears as text. But after a couple of runs, the file somehow gets converted to a binary file. Do you suspect anything from your code will touch this file?

**Comment by StarpTech** [comment]
I can't reproduce it.

**Comment by StarpTech** [comment]
@veeramarni still an issue?
